#!/bin/bash

if [ -f "platforms/android/AndroidManifest.xml" ]; then
    echo "Changing 'windowSoftInputMode' from 'adjustResize' to 'adjustPan' in AndroidManifest.xml to prevent flickering"
    sed -i 's/android:windowSoftInputMode="adjustResize"/android:windowSoftInputMode="adjustPan"/' platforms/android/AndroidManifest.xml
fi
